### ISSUE TITLE
Extract bisq-network/exchange 'provider' module to top-level bisq-network/pricenode repository

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq-pricenode-deprecated#2]
This work began last August in https://github.com/bisq-network/pricenode and got sidelined. The work is mostly complete there. This issue includes the following:

 - [x] sync `bisq-network/pricenode` with with latest (`v0.6.4`) version of `pricenode` module sources
 - [x] set the version of the new `pricenode` project to `v0.7.0`
 - [x] migrate production pricenodes to `v0.7.0`
 - [x] remove the `pricenode` module from the bisq-network/exchange repo

**Comment by cbeams** [comment]
Closing as complete. All pricenodes have been upgraded to the new repository. Thanks everyone.
